### ISSUE TITLE
no data connection on  pro mini at328p

### ISSUE THREAD

**Issue by richardmlea** [Dubstaaa/NeatDash-#2]
Hi, I am trying to use this but I can't get a data connection. The screen is working but says there is no data connection. 
Could you look at my work and see if you can spot what I have done wrong?
Here's a couple of images of what I have done.
![IMG_20220925_103017](https://user-images.githubusercontent.com/83568704/192137978-4fc215b8-2fbe-473f-883d-5c1693d56ebe.jpg)
![IMG_20220925_103211](https://user-images.githubusercontent.com/83568704/192137986-e3bdf89d-8e08-4546-ad26-12d4dcddfe0a.jpg)
Can you see any issues with it
I am using a mini pro at328p that has no icsp pins so I am connecting the data and ground from the scooter to the bottom of pins 11 and 12 respectively and the resistor and diode to the other side of the board. I think this is doing the same as your connections.
I am running the LCD at 5v as my Arduino has no 3.3v. could this be causing an issue? The screen seems to be working at 5v but could this cause an issue with the data connection?
Also, I am using it on a m365 pro dashboard is this ok or is it just for the standard m365?
Thanks

**Comment by Dubstaaa** [comment]
I apologize for the delay in my answer. Linking display Vcc pin directly to arduino's 5v pin may cause watchdog FAILURE. If watchdog does not work properly the board continuously tries to restore the connection on bus. Only when a proper connection is established the program would run.
You can check this connecting LCD on a separate supply: if a valid connection starts, data will appear immediately after the bootlogo.

**Comment by Dubstaaa** [comment]
No, in your case instead of the watchdog failure I'm quite sure that the problem is caused by your connection on bus.
Diode and Resistor are well connected, but D11 must be linked on scooter bus (yellow wire on Xiaomi models) and STOP. Gnd does not have to be connected on D12. In order to work properly the system requires Scooter Gnd liked to Arduino Gnd pin.
So try first to remove gnd wire on D12 pin. 
Hope it can help!

**Comment by richardmlea** [comment]
Hi, Thanks for the reply.
Moving the Ground wire from D12 to the Ground on the Arduino fixed the issue and it appears to be working now. 
If I have watchdog failures I will power the LCD from the BLE but it seems to be working as is.
I will test when it stops raining and update here if I needed to change it.
Thanks again.

**Comment by richardmlea** [comment]
It stopped raining for half an hour for me to test it and everything is working  really well. No hangs or reboots.
Would it be possible to add a feature to suspend the Arduino at boot with the brake and throttle so the BLE firmware can be updated without disconnecting the Arduino?

**Comment by Dubstaaa** [comment]
Sure! If you use my firmware, this is an already installed feature. 

Try this:

¬Open your favorite BLE app (I recommend you to download Scooter Hacking Utility due to its infinite possibilities). 

¬Power on your scooter

¬**Suddenly after booting, before the bootlogo disappear** press full throttle and full brake, then release brake control and still pressing throttle. 

¬The scooter is now visible on BLE app, you can release throttle control.
Regrettably at this stage Arduino display acts as normal, does not inform you on downloading process. 

You are now able to update your ble Firmware.
